language: julia

julia:
  - 1.0
  - 1

os:
  - linux
  - osx

after_success:
  - julia --project -e 'import Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include("docs/make.jl")'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
